---
- name: For Azure learn
  hosts: localhost
  connection: local
  roles:
  - azure_preview_modules
  vars:
    resource_group: myRG02
    location: "east us"
    virtualnetwork: virtualnetwork01
    subnet: subnet01
    public_ip: public_ip01
    security_ssh: security_ssh01
    test_nic: test_nic01
    vm_name: myVM01
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6RUJHaZHn5mzhHGdsymPW7p5tymtGy761uw1RAAH9aM498PNPQMwyw+kgG8ZaGiEGyzNAlzNYCzTdQ41j8nG1g7p+wEc0BWBWueGONM8fSaROqadSYZjafBEYywxEDED4q2UlRN90sGnW6TC2ldae3XgaUlQ6V1hlwm/Hr2FA8A5tek20KsZT3f0XycIcvXu40f5HRT7I2QuBtpD8E46jn3WRRAC4cmU35TMYEmAeY9X9IZplLIPiRJENO7gi6BnYNn5siiOd6MrZ18sEkz6lzfDtiqqkN/Axoa4f1nipgB9DcZRN5iaNvepynwAMklyk5gsCDqvc03sm6n8PZlzB fred@fred-Virtual-Machine"
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
  
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      name: "{{ test_nic }}"
      resource_group: "{{ resource_group }}"
      virtual_network_name: "{{ virtualnetwork }}"
      location: "east us"
      subnet_name: "{{ subnet }}"
      security_group_name: "{{ security_ssh }}"
      public_ip: no

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Basic_A0
      admin_username: deploy
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/deploy/.ssh/authorized_keys
          key_data: "{{ public_key }}"
      network_interfaces: "{{ test_nic }}"
      location: "east us"
      image:
        offer: "CentOS"
        publisher: "OpenLogic"
        sku: "7.4"
        version: "latest"
