---
- name: For test 85
  hosts: localhost
  connection: local
  vars:
    resource_group: myRG
    location: westeurope
    virtualnetwork: virtualnetwork
    subnet: subnet
    public_ip: public_ip
    security_ssh: security_ssh
    test_nic: test_nic
    vm_name: myVM
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "172.16.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "172.16.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
 
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ test_nic }}"
      subnet: "{{ subnet }}"
      security_group_name: "{{ security_ssh }}"
      ip_configurations:
        - name: primary
          private_ip_allocation_method: Static
          private_ip_address: '172.16.1.42'
          primary: True
      virtual_network_name: "{{ virtualnetwork }}"
    register: nic_dump
  - name: dump nic data
    debug:
      var: nic_dump
