---
# Resource_group and image has create before excute
- name: For Azure learn
  hosts: localhost
  connection: local
  vars:
    resource_group: myRG06  
    location: westeurope
    virtualnetwork: virtualnetwork
    subnet: subnet
    public_ip: public_ip
    storageaccount: sssaaa02
    security_ssh: security_ssh
    test_nic: test_nic
    vm_name: myVM
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storageaccount }}"
      account_type: Standard_LRS

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
  
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ test_nic }}"
      virtual_network: "{{ virtualnetwork }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ public_ip}}"
      security_group: "{{ security_ssh }}"

  - name: create an availability set with default options 
    azure_rm_availabilityset:
      name: availability_set
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
#      platform_update_domain_count: 5
#      platform_fault_domain_count: 3
      sku: Aligned
  - name: create virtual machine
    azure_rm_virtualmachine: 
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      auth_source: cli
      availability_set: availability_set
      vm_size: Standard_A0
      managed_disk_type: Standard_LRS
      storage_account: "{{ storageaccount }}"
      admin_username: azureuser
      admin_password: Password@0329
      network_interface_names: "{{ test_nic }}"
#      state: present
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/azureuser/.ssh/authorized_keys"
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6RUJHaZHn5mzhHGdsymPW7p5tymtGy761uw1RAAH9aM498PNPQMwyw+kgG8ZaGiEGyzNAlzNYCzTdQ41j8nG1g7p+wEc0BWBWueGONM8fSaROqadSYZjafBEYywxEDED4q2UlRN90sGnW6TC2ldae3XgaUlQ6V1hlwm/Hr2FA8A5tek20KsZT3f0XycIcvXu40f5HRT7I2QuBtpD8E46jn3WRRAC4cmU35TMYEmAeY9X9IZplLIPiRJENO7gi6BnYNn5siiOd6MrZ18sEkz6lzfDtiqqkN/Axoa4f1nipgB9DcZRN5iaNvepynwAMklyk5gsCDqvc03sm6n8PZlzB fred@fred-Virtual-Machine"
      image: 
        offer: vmseries1
        publisher: paloaltonetworks
        sku: bundle2
        version: '8.1.0'
      plan:
        publisher: paloaltonetwords
        product: vmseries1
        name: bundle2

#      image:
#        offer: UbuntuServer
#        publisher: Canonical
#        sku: 16.04-LTS
#        version: latest
#      plan:
#        publisher: Canonical
#        product: UbuntuServer
#        name: 16.04-LTS
