# This is the configuration template for ansible-test Azure integration tests.
#
# You do not need this template if you are:
#
# 1) Running integration tests without using ansible-test.
# 2) Using the automatically provisioned Azure credentials in ansible-test.
#
# If you do not want to use the automatically provisioned temporary Azure credentials,
# fill in the values below and save this file without the .template extension.
# This will cause ansible-test to use the given configuration instead of temporary credentials.
#
# NOTE: Automatic provisioning of Azure credentials requires one of:
#       1) ansible-core-ci API key in ~/.ansible-core-ci.key
#       2) Sherlock URL (including API key) in ~/.ansible-sherlock-ci.cfg

# Provide either Service Principal or Active Directory credentials below.

# Service Principal
AZURE_CLIENT_ID: ae12946a-f4de-4609-a5d1-68c36604f3b0
AZURE_SECRET: KcDB6CMlNn+MmtA+ZJv6xXmXQz+x2JRxGQBy6Dh6adw=
AZURE_SUBSCRIPTION_ID: 2085065b-00f8-4cba-9675-ba15f4d4ab66
AZURE_TENANT: 72f988bf-86f1-41af-91ab-2d7cd011db47

# Active Directory
AZURE_AD_USER: fred
AZURE_PASSWORD: Fred0329
AZURE_SUBSCRIPTION_ID: 2085065b-00f8-4cba-9675-ba15f4d4ab66

# Resource Groups
RESOURCE_GROUP: myRG03
RESOURCE_GROUP_SECONDARY: myRG04
